#!/bin/sh
# Pack the clips into sounds-data.js: the view's sandbox can't fetch its own files, but it can
# load a script, so the clips ride in one as base64. Run after changing any .ogg here.
cd "$(dirname "$0")" || exit 1
{
  echo '// Generated by pack.sh from the .ogg files beside it (CC0: see CREDITS.md). Do not edit.'
  echo 'window.SOUND_DATA = {'
  for f in *.ogg; do printf '  "%s": "%s",\n' "${f%.ogg}" "$(base64 < "$f" | tr -d '\n')"; done
  echo '};'
} > sounds-data.js
echo "sounds-data.js: $(wc -c < sounds-data.js) bytes"
